version: 2.1

orbs:
  python: circleci/python@2

jobs:
  build_exo_macos:
    macos:
      xcode: "16.0.0"
    resource_class: m2pro.large
    steps:
      - checkout
      - run:
          name: Clone exo Git repo and Qwen-2.5-0.5B
          command: |
            git clone https://github.com/exo-explore/exo.git exo-backend
      - run:
          name: Set up Python environment
          command: |
            brew install python@3.12
            cd exo-backend
            python3.12 -m venv env
      - run:
          name: Install dependencies
          command: |
            cd exo-backend
            source env/bin/activate
            pip install --upgrade pip
            pip install .
      - run:
          name: Build exo for macOS
          command: |
            cd exo-backend
            source env/bin/activate
            python3 scripts/build_exo.py
      - run:
          name: Move exo executable to root
          command: |
            mkdir -p ./Binaries/main.dist
            mv ./exo-backend/dist/main.dist ./Binaries/main.dist
            
  publish_github_release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish Release on GitHub
          command: |
            VERSION=$(basename $(ls exo-v*.dmg) .dmg | sed 's/^exo-v//')
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} v${VERSION} "exo-v${VERSION}.dmg"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_exo_macos:
        filters:
          tags:
            only: /.*/
          branches:
            only: /.*/

